#!/usr/bin/env bash
set -euo pipefail

version=""
repo="${HOPTER_RELEASE_REPOSITORY:-sorcererxw/hopter}"
checksums=""
output=""

usage() {
  cat <<'EOF'
Usage:
  scripts/generate-homebrew-formula.sh --version v0.0.1 --checksums release/checksums.txt --output Formula/hopter.rb

Options:
  --version      Release version, with or without leading v
  --repo         GitHub release repository, default: sorcererxw/hopter
  --checksums    Path to checksums.txt generated by the release workflow
  --output       Output formula path
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version)
      version="${2:-}"
      shift 2
      ;;
    --repo)
      repo="${2:-}"
      shift 2
      ;;
    --checksums)
      checksums="${2:-}"
      shift 2
      ;;
    --output)
      output="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "$version" || -z "$checksums" || -z "$output" ]]; then
  usage >&2
  exit 2
fi

if [[ ! -f "$checksums" ]]; then
  echo "checksums file not found: $checksums" >&2
  exit 1
fi

version="${version#v}"
tag="v${version}"

checksum_for() {
  local asset="$1"
  awk -v asset="$asset" '$2 == asset { print $1; found = 1 } END { if (!found) exit 1 }' "$checksums"
}

darwin_amd64="$(checksum_for hopter-darwin-amd64)"
darwin_arm64="$(checksum_for hopter-darwin-arm64)"
linux_amd64="$(checksum_for hopter-linux-amd64)"
linux_arm64="$(checksum_for hopter-linux-arm64)"

mkdir -p "$(dirname "$output")"

cat > "$output" <<EOF
class Hopter < Formula
  desc "Self-hosted remote control plane for local coding agents"
  homepage "https://github.com/${repo}"
  license "Apache-2.0"
  version "${version}"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/${repo}/releases/download/${tag}/hopter-darwin-arm64"
      sha256 "${darwin_arm64}"
    else
      url "https://github.com/${repo}/releases/download/${tag}/hopter-darwin-amd64"
      sha256 "${darwin_amd64}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/${repo}/releases/download/${tag}/hopter-linux-arm64"
      sha256 "${linux_arm64}"
    else
      url "https://github.com/${repo}/releases/download/${tag}/hopter-linux-amd64"
      sha256 "${linux_amd64}"
    end
  end

  def install
    source = Dir["hopter-*"].first
    bin.install source => "hopter"
  end

  service do
    run [opt_bin/"hopter", "serve"]
    keep_alive true
    log_path var/"log/hopter.log"
    error_log_path var/"log/hopter.err.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hopter version")
  end
end
EOF

echo "Generated Homebrew formula: $output"
