// Code generated by platform/scripts/generate-relay-contract.mjs; DO NOT EDIT.
// Shared relay contract source of truth for platform TypeScript and hopter Go.


package relaycontract

const RelayProtocolVersion = 1

var RelayCapabilities = []string{
	"http-request-stream",
	"sse-response-stream",
	"terminal-websocket",
	"session-token-refresh",
}

var RelayMessageTypes = []string{
	"relay-ready",
	"client-ready",
	"relay-accepted",
	"request-start",
	"request-body",
	"request-end",
	"response-start",
	"response-body",
	"response-end",
	"websocket-connect",
	"websocket-accept",
	"websocket-reject",
	"websocket-frame",
	"websocket-close",
	"error",
	"ping",
	"pong",
}

type RelayMessageType string

const (
	RelayMessageTypeRelayReady RelayMessageType = "relay-ready"
	RelayMessageTypeClientReady RelayMessageType = "client-ready"
	RelayMessageTypeRelayAccepted RelayMessageType = "relay-accepted"
	RelayMessageTypeRequestStart RelayMessageType = "request-start"
	RelayMessageTypeRequestBody RelayMessageType = "request-body"
	RelayMessageTypeRequestEnd RelayMessageType = "request-end"
	RelayMessageTypeResponseStart RelayMessageType = "response-start"
	RelayMessageTypeResponseBody RelayMessageType = "response-body"
	RelayMessageTypeResponseEnd RelayMessageType = "response-end"
	RelayMessageTypeWebsocketConnect RelayMessageType = "websocket-connect"
	RelayMessageTypeWebsocketAccept RelayMessageType = "websocket-accept"
	RelayMessageTypeWebsocketReject RelayMessageType = "websocket-reject"
	RelayMessageTypeWebsocketFrame RelayMessageType = "websocket-frame"
	RelayMessageTypeWebsocketClose RelayMessageType = "websocket-close"
	RelayMessageTypeError RelayMessageType = "error"
	RelayMessageTypePing RelayMessageType = "ping"
	RelayMessageTypePong RelayMessageType = "pong"
)

type RelayWebSocketOpcode string

const (
	RelayWebSocketOpcodeText RelayWebSocketOpcode = "text"
	RelayWebSocketOpcodeBinary RelayWebSocketOpcode = "binary"
)

const (
  RelayRequestContextPayloadHeader = "x-hopter-relay-context"
  RelayRequestContextSignatureHeader = "x-hopter-relay-signature"
)

type RelaySessionTokenPayload struct {
  AuthUserId string `json:"authUserId"`
  WorkspaceSlug string `json:"workspaceSlug"`
  LeaseId string `json:"leaseId"`
  LeaseVersion int64 `json:"leaseVersion"`
  RouteGeneration int64 `json:"routeGeneration"`
  SessionId string `json:"sessionId"`
  Exp int64 `json:"exp"`
}

type RelayRequestContext struct {
  AuthUserId string `json:"authUserId"`
  WorkspaceSlug string `json:"workspaceSlug"`
  LeaseId string `json:"leaseId"`
  LeaseVersion int64 `json:"leaseVersion"`
  RouteGeneration int64 `json:"routeGeneration"`
  Exp int64 `json:"exp"`
  Nonce string `json:"nonce"`
}

type RelayHeaderMap map[string]string

type RelayReadyMessage struct {
  Type            RelayMessageType `json:"type"`
  ProtocolVersion int              `json:"protocolVersion"`
  Capabilities    []string         `json:"capabilities"`
}

type ClientReadyMessage struct {
  Type            RelayMessageType `json:"type"`
  ProtocolVersion int              `json:"protocolVersion"`
  Capabilities    []string         `json:"capabilities"`
}

type RelayAcceptedMessage struct {
  Type             RelayMessageType `json:"type"`
  ProtocolVersion  int              `json:"protocolVersion"`
  Capabilities     []string         `json:"capabilities"`
  SessionExpiresAt int64            `json:"sessionExpiresAt"`
}

type RequestStartMessage struct {
  Type       RelayMessageType    `json:"type"`
  StreamID   string              `json:"streamId"`
  Method     string              `json:"method"`
  Path       string              `json:"path"`
  Query      string              `json:"query"`
  Headers    RelayHeaderMap      `json:"headers"`
  Provenance RelayRequestContext `json:"provenance"`
}

type RequestBodyMessage struct {
  Type       RelayMessageType `json:"type"`
  StreamID   string           `json:"streamId"`
  DataBase64 string           `json:"dataBase64"`
}

type RequestEndMessage struct {
  Type     RelayMessageType `json:"type"`
  StreamID string           `json:"streamId"`
}

type ResponseStartMessage struct {
  Type     RelayMessageType `json:"type"`
  StreamID string           `json:"streamId"`
  Status   int              `json:"status"`
  Headers  RelayHeaderMap   `json:"headers"`
}

type ResponseBodyMessage struct {
  Type       RelayMessageType `json:"type"`
  StreamID   string           `json:"streamId"`
  DataBase64 string           `json:"dataBase64"`
}

type ResponseEndMessage struct {
  Type     RelayMessageType `json:"type"`
  StreamID string           `json:"streamId"`
}

type WebSocketConnectMessage struct {
  Type       RelayMessageType    `json:"type"`
  StreamID   string              `json:"streamId"`
  Path       string              `json:"path"`
  Query      string              `json:"query"`
  Headers    RelayHeaderMap      `json:"headers"`
  Provenance RelayRequestContext `json:"provenance"`
}

type WebSocketAcceptMessage struct {
  Type     RelayMessageType `json:"type"`
  StreamID string           `json:"streamId"`
  Headers  RelayHeaderMap   `json:"headers"`
}

type WebSocketRejectMessage struct {
  Type     RelayMessageType `json:"type"`
  StreamID string           `json:"streamId"`
  Status   int              `json:"status"`
  Message  string           `json:"message"`
}

type WebSocketFrameMessage struct {
  Type       RelayMessageType     `json:"type"`
  StreamID   string               `json:"streamId"`
  Opcode     RelayWebSocketOpcode `json:"opcode"`
  DataBase64 string               `json:"dataBase64"`
}

type WebSocketCloseMessage struct {
  Type     RelayMessageType `json:"type"`
  StreamID string           `json:"streamId"`
  Code     int              `json:"code"`
  Reason   string           `json:"reason"`
}

type RelayErrorMessage struct {
  Type     RelayMessageType `json:"type"`
  StreamID string           `json:"streamId,omitempty"`
  Code     string           `json:"code"`
  Message  string           `json:"message"`
}

type PingMessage struct {
  Type   RelayMessageType `json:"type"`
  SentAt int64            `json:"sentAt"`
}

type PongMessage struct {
  Type   RelayMessageType `json:"type"`
  SentAt int64            `json:"sentAt"`
}
